import { v4 as uuidv4 } from 'uuid';

// Type definitions for Cenopiee application
export interface CompanyData {
  id: string;
  _id?: string; // MongoDB ObjectId
  userId?: string;
  type?: 'startup' | 'small' | 'medium-large' | 'enterprise';
  name: string;
  email?: string;
  website?: string;
  industry: string;
  size?: string;
  businessType?: string;
  logo?: string | null;
  coverImage?: string | null;
  description?: string;
  founded?: string;
  headquarters?: string;
  employees?: string;
  businessRegistration?: string;
  taxId?: string;
  contactPerson?: string;
  contactPhone?: string;
  status?: 'pending' | 'approved' | 'rejected';
  adminNotes?: string;
  approvedAt?: string;
  approvedBy?: string;
  isBlacklisted?: boolean;
  blacklistReason?: string;
  blacklistedAt?: string;
  createdAt: string;
  isApproved?: boolean;
  isVerified?: boolean;
  news?: CompanyNews[];
}

// For creating companies, ID is generated by the backend
export type CompanyCreationData = Omit<CompanyData, 'id'>;

export interface CompanyNews {
  id: string;
  companyId: string;
  title: string;
  content: string;
  imageUrl?: string;
  publishedAt: string;
  isTopNews?: boolean;
}

export interface JobPosting {
  id: string;
  _id?: string; // MongoDB ObjectId
  companyId: string;
  userId?: string;
  title: string;
  department: string;
  location: string;
  type: 'Full-time' | 'Part-time' | 'Contract' | 'Internship';
  description: string;
  requirements: string[];
  salary: string;
  experience: string;
  benefits: string[];
  status: 'active' | 'paused' | 'closed';
  applicants: number;
  views: number;
  postedAt: string;
  companyDescription?: string;
}

export interface UserData {
  id: string;
  _id?: string; // MongoDB ObjectId
  name: string;
  email: string;
  profileImage?: string;
  bio?: string;
  headline?: string;
  location?: string;
  isVerified?: boolean;
  isBlacklisted?: boolean;
  blacklistReason?: string;
  blacklistedAt?: string;
  joinedAt: string;
  lastActive?: string;
}

export interface ApplicationData {
  id: string;
  jobId: string;
  userId: string;
  companyId: string;
  status: 'pending' | 'reviewed' | 'accepted' | 'rejected';
  resume: string | null;
  coverLetter: string;
  appliedAt: string | Date;
  createdAt: string | Date;
  updatedAt: string | Date;
}

// Utility function for generating user IDs (now handled by auth store)
export const generateUserId = (): string => {
  return uuidv4();
};

// Legacy function for backward compatibility
export const getUserId = generateUserId;
